local r3_core = require "r3.core"

local METHOD_GET = 2
local tree = r3_core.r3_create(10)
print(tree)
local node2 = r3_core.r3_insert(tree, METHOD_GET, "/2/{id}", 4)
local node3 = r3_core.r3_insert(tree, METHOD_GET, "/2/{name}", 100)
local node4 = r3_core.r3_insert(tree, METHOD_GET, "/2", 3)
print(node1)
print(node2)
print(node3)
local ok,msg = r3_core.r3_compile(tree)
print(ok, msg)
local idx = r3_core.r3_match_route(tree, "/1", METHOD_GET)
print(idx)
local idx = r3_core.r3_match_route(tree, "/2", METHOD_GET)
print(idx)
local idx = r3_core.r3_match_route(tree, "/2/i", METHOD_GET)
print(idx)
r3_core.r3_free(tree)
